// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Clock(Props) {
  var match = React.useState((function () {
          return Date.now();
        }));
  var setDate = match[1];
  React.useEffect((function () {
          var timerID = setInterval((function (param) {
                  return Curry._1(setDate, (function (param) {
                                return Date.now();
                              }));
                }), 1000);
          return (function (param) {
                    clearInterval(timerID);
                    return /* () */0;
                  });
        }));
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Hello, world!"), React.createElement("h2", undefined, "It is " + (new Date(match[0]).toLocaleTimeString() + ".")));
}

var make = Clock;

exports.make = make;
/* react Not a pure module */
