// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var AnalogClock$ReasonUseClockHook = require("./AnalogClock.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(AnalogClock$ReasonUseClockHook.make, { }), "use-clock");

/*  Not a pure module */
