// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function useClock(param) {
  var match = React.useState((function () {
          return Date.now();
        }));
  var setDate = match[1];
  React.useEffect((function () {
          var ticker = setInterval((function (param) {
                  return Curry._1(setDate, (function (param) {
                                return Date.now();
                              }));
                }), 1000);
          return (function (param) {
                    clearInterval(ticker);
                    return /* () */0;
                  });
        }));
  return match[0];
}

exports.useClock = useClock;
/* react Not a pure module */
